// <auto-generated />
namespace Forms_Lab2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Data_with_city : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Data_with_city));
        
        string IMigrationMetadata.Id
        {
            get { return "202204031818349_Data_with_city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
